### ISSUE TITLE
Update legal pages with correct billing frequency

### ISSUE THREAD

**Issue by gbp** [mysociety/asktheeu-theme#105]
Following on from #77 and #96 

Currently T&C refers to monthly billing but only yearly plans are on offer.

**Comment by garethrees** [comment]
https://github.com/mysociety/asktheeu-theme/tree/master/lib/views/alaveteli_pro/pages in the `_legal.LOCALE.html.erb`

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/asktheeu-theme/pull/113.
