### ISSUE TITLE
AskTheEU language switcher issue

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/asktheeu-theme#106]
When visiting asktheeu.org on May 18th 2020 using the Chrome browser the site would only display content in Spanish or German, regardless of which language was selected:
<img width="1396" alt="Screenshot 2020-05-18 at 12 10 01" src="https://user-images.githubusercontent.com/4170351/82206756-b68d8880-9900-11ea-988d-83c05e2bc891.png">

& 

<img width="1396" alt="Screenshot 2020-05-18 at 12 12 27" src="https://user-images.githubusercontent.com/4170351/82206874-e63c9080-9900-11ea-885f-f4f47071cc71.png">

Also tested by @wrightmartin on Firefox and Safari - same issue showing. Reselecting the language seemed to help though wasn't consistent.

Linked to: https://github.com/mysociety/alaveteli/issues/5484

**Comment by gbp** [comment]
Still seems to be an issue here.

**Comment by gbp** [comment]
Seems to be working now. I was probably seeing cached output before
