### ISSUE TITLE
Upgrade to version 0.43.x

### ISSUE THREAD

**Issue by garethrees** [mysociety/asktheeu-theme#123]
Made available on 28 April 2023: https://github.com/mysociety/alaveteli/releases/tag/0.43.0.0

Might be a slightly newer version available that includes background attachment processing, but unsure of version number at time of writing/

**Comment by gbp** [comment]
### 0.41.1.1

- [ ] `alaveteli-update-general-config 0.41.1.1 /data/servers/vhosts/alaveteli/<vhost>/config_general.yml.ugly`
- [ ] bump ruby to 2.7.7
- [ ] add "storage/" to `SHARED_DIRECTORIES` in general config
- [ ] replace backup_dirs "raw_emails" with "shared/storage/raw_emails" in servers JSON
- [ ] deploy
- [x] ~~`bin/rails db:migrate`~~ - done automatically on mysoc deploy
- [ ] `bin/rails temp:remove_orphan_raw_email_records`
- [ ] `bin/rails temp:populate_incoming_message_from_email`
- [x] ~~add config/storage.yml~~ - done for mysoc servers already
- [ ] `bin/rails storage:migrate`

### 0.42.0.1

- [x] ~~`alaveteli-update-general-config 0.42.0.1 /data/servers/vhosts/alaveteli/<vhost>/config_general.yml.ugly`~~ - not needed, no changes to `general.yml` in this release
- [ ] deploy
- [x] ~~`bin/rails db:migrate`~~ - done automatically on mysoc deploy
- [ ] `bin/rails temp:migrate_public_body_notes`
- [ ] `bin/rails temp:convert_syck_to_psych_yaml`
- [ ] `bin/rails temp:fix_old_objects_in_yaml`
- [ ] `bin/rails temp:sanitise_and_populate_events_params_json`
- [ ] `bin/rails runner "p InfoRequestEvent.where(params: nil).count"` should be zero
- [ ] `bin/rails runner "PublicBody.without_request_email.each(&:save)"`

### 0.43.0.1

- [ ] `alaveteli-update-general-config 0.43.0.1 /data/servers/vhosts/alaveteli/<vhost>/config_general.yml.ugly`
- [ ] bump ruby to 3.2.0
- [ ] add `"<vhost-user>-sidekiq": "sidekiq.service.ugly"` to daemons in servers JSON
- [ ] assign Redis database number to vhost, see: https://wiki.mysociety.org/wiki/Redis#Databases_and_Namespaces
- [ ] update wiki and `/data/servers/vhosts/alaveteli/config_rails_env.rb.ugly`
- [ ] deploy
- [x] ~~`bin/rails db:migrate`~~ - done automatically on mysoc deploy

### wrapup/cleanup

- [ ] check new `/data/servers/<vhost>/shared/storage/raw_emails` dir is being backed up
- [ ] remove old raw emails backup?
- [ ] at some point, run: `rm -rf /data/servers/<vhost>/raw_emails`

**Comment by garethrees** [comment]
@gbp did the cleanup stuff happen here? If so, can this be closed?

**Comment by gbp** [comment]
> @gbp did the cleanup stuff happen here? If so, can this be closed?

Moved to https://github.com/mysociety/sysadmin/issues/1934
