### ISSUE TITLE
Incorrect link to "Alaveteli" in site footer

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/asktheeu-theme#17]
On http://www.asktheeu.org/, the link to "Alaveteli" in the string "A project by Access Info Europe, powered by Alaveteli" goes to https://alaveteli.org/, which doesn't exist. It should probably be http://alaveteli.org/ (no HTTPS).

**Comment by garethrees** [comment]
Fixed in 4e2a9a96c235beace20ff8ff3118727ce471f18e
