### ISSUE TITLE
iOS 7: Bottom 200px of homepage hero is unclickable because of YouTube iframe?

### ISSUE THREAD

**Issue by zarino** [mysociety/asktheeu-theme#19]
Steps to reproduce:
- Open the AskTheEU homepage on an iPhone running iOS 7.1.2
- Try clicking the green "Send a request" button or the "Find out more" link, or try selecting some of the text in the _last two lines_ of the hero text.
- Note how your clicks and selections have no effect. The links cannot be followed, and the text cannot be selected.

By adding a `touchstart` listener to the document, I've been able to determine that the `touchstart` event isn't firing when these elements are touched, or when scrolls are begun inside this area.

![iframe](https://cloud.githubusercontent.com/assets/739624/12588074/da192b32-c44e-11e5-80a7-3085b2b29d41.png)

The "non-responsive" area is—as best as I can tell—exactly the same size as the YouTube iframe, 330px further down the page. Indeed, removing the YouTube iframe fixes the problem.

I assumed it must be my `.responsive-iframe` classes that were messing the layout up, so I removed the `responsive-iframe` wrapper, and gave the iframe plain width and height attributes, to match the size it should be on the iPhone screen:

```
<iframe width="290" height="163" src="https://www.youtube-nocookie.com/embed/0NBuYOPZn_4?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen=""></iframe>
```

But that didn't make any difference. Even without the `.responsive-iframe` stuff, the area above was still unclickable.

iOS 8 and iOS 9 appear to be unaffected.

**Comment by zarino** [comment]
A minimal webpage that exhibits the bug on iOS 7:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
    html {
      font-family: sans-serif;
      -ms-text-size-adjust: 100%;
      -webkit-text-size-adjust: 100%;
    }

    body {
      margin: 0;
    }

    .wrapper {
      padding: 1em;
      max-width: 480px;
      margin: 0 auto;
    }

    .responsive-iframe {
      width: 100%;
      position: relative;
      height: 0;
      padding-top: 100%;
    }

    .responsive-iframe iframe {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }

    .responsive-iframe--16-9 {
      padding-top: 56.25%;
    }

    .js-spot {
      position: absolute;
      top: -99px;
      display: block;
      width: 10px;
      height: 10px;
      background: rgba(255, 0, 0, 0.5);
      border-radius: 100%;
      margin: -5px 0 0 -5px;
    }
    </style>
  </head>
  <body>

    <div class="wrapper">

      <p>Try tapping me</p>
      <p>The little red dot…</p>
      <p>…Should follow your taps</p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>
      <p>Bet you can’t tap me!</p>
      <p>Bet you <a href="/">can’t tap me!</a></p>
      <p>Bet you can’t tap me!</p>
      <p>Bet you can’t tap me!</p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>
      <p>Try <a href="/">tapping me</a></p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>

      <div class="responsive-iframe responsive-iframe--16-9">
        <iframe width="1280" height="720" src="https://www.youtube-nocookie.com/embed/0NBuYOPZn_4?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
      </div>

      <p>Try tapping me</p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>
      <p>Try tapping me</p>

    </div>

    <div class="js-spot"></div>

    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script>
    $(function(){
      $(document).on('touchstart', function(e){
        console.log(e);
        var xPos = e.originalEvent.touches[0].pageX;
        var yPos = e.originalEvent.touches[0].pageY;
        $('.js-spot').css({
          "top": yPos,
          "left": xPos
        });
      });
    });
    </script>

  </body>
</html>
```

**Comment by garethrees** [comment]
> I checked my iOS and it is indeed 7.1.2, so that might be what's causing the trouble. The weird thing is that **while the page is loading, I can click the button. But once it is fully loaded, I can't**, as if it wasn't a button any more. Does this make any sense to you?

**Comment by garethrees** [comment]
Might be relevant http://stackoverflow.com/questions/9074365/youtube-video-embedded-via-iframe-ignoring-z-index

**Comment by garethrees** [comment]
This seems to work now, at least on my iPhone SE with the most recent iOS 13.
