### ISSUE TITLE
Missing help page sections

### ISSUE THREAD

**Issue by garethrees** [mysociety/asktheeu-theme#25]
AskTheEU is missing some of the [required help sections](http://alaveteli.org/docs/customising/themes/#customising-the-help-pages).

#### Wrong place

- `/help/credits#helpus`  
AskTheEU has a custom [help out page](http://www.asktheeu.org/en/help/help_out). We can either merge this content back in to `/help/credits`, or change the link

#### Don't exist
- `/help/requesting#quickly_response`  
Goes to "How long do I have to submit an appeal", rather than "How quickly will I get a response?". There's no section for how long the authorities have to respond

- `/help/requesting#missing_body`  
There's no section for missing bodies

**Comment by garethrees** [comment]
Emailed Andreas about these. He's away until 8th April, so we won't see any action before then, and I expect its something they'll build in to future help page updates.

**Comment by andreaspavlou** [comment]
Hi Gareth 

Please keep the 'can i help out?' page as is, if that is not too much of a pain when it comes to updating the website. 

/help/requesting#quickly_response
- this would be better if it were to direct readers to the question "How do I submit a request?" (and if possible, specifically to the second bullet point that mentions 15 working days)

/help/requesting#missing_body
- this should direct you to: "To which EU body should I make a request?" and if possible, add a fourth bullet point that says: "Please contact us if you think AsktheEU.org is missing an EU institution that comes under EU transparency rules!"

thanks !

**Comment by lizconlan** [comment]
Fixed in #40
