### ISSUE TITLE
Making AsktheEU.org match EU lingo

### ISSUE THREAD

**Issue by andreaspavlou** [mysociety/asktheeu-theme#31]
Hi All,

We were wondering how easy it is to make the following changes to text that appears in AsktheEU.org:

**CURRENT TEXT ==> NEW TEXT**
internal review ==> confirmatory application  
(e.g in subject of email to send internal review, or text in messages to make internal review to say instead “confirmatory application”)

FOI / Freedom of Information ==> access to documents
(e.g in subject of initial request email)

There might be more as we find random words in places :)

Thanks!

**Comment by garethrees** [comment]
#39 Fixes the regression of "Freedom of Information" appearing.

There's some currently unresolved discussion around changing wording to "confirmatory application" in https://github.com/mysociety/asktheeu-theme/pull/39#issuecomment-222666548.

**Comment by lizconlan** [comment]
#39 merged but not deployed, Transifex updated with new translation definitions

**Comment by garethrees** [comment]
> #39 merged but not deployed, Transifex updated with new translation definitions

Is this deployed now?

**Comment by lizconlan** [comment]
Site redeployed 05/07/2016 17:00

**Comment by lizconlan** [comment]
more on confirmatory application
* http://www.wobbing.eu/news/eu-confirmatory-application-step-step
* http://blogs.bmj.com/bmj/files/2014/09/jim-Appeal-against-refusal.pdf

**Comment by andreaspavlou** [comment]
Hi all, just to add that the automatic text for appeals/internal reviews in AsktheEU.org would need to be changed as well (just noticed this)

We would basically want to change it to:
"
Dear INSTITUTION,

Please pass this on to the person who reviews confirmatory applications.

I am filing the following confirmatory application with regards my access to documents request 'XXXXXXXXXXXXXX'.

[ GIVE DETAILS ABOUT YOUR COMPLAINT HERE ] 
"
Thanks!!

**Comment by lizconlan** [comment]
Current screenshot of the internal review/confirmatory application page:

![screen shot 2016-09-16 at 14 24 08](https://cloud.githubusercontent.com/assets/27760/18587435/f98c416a-7c19-11e6-94b6-e8eeff342007.png)
