### ISSUE TITLE
require ´space´ when entering username

### ISSUE THREAD

**Issue by andreaspavlou** [mysociety/asktheeu-theme#33]
Hi all,

The EU institutions have brought to our attention some odd and ´nuisance´ requests which we notice have only got one ´name´ in their username. We think it would be better for AsktheEU.org if it were to require a first and last name from users when registering, as we ask people to do so in our About pages.

Therefore, it would be great if when creating an account, that users are obliged to put in a first name and surname. Since it is not easy to have two fields, instead (as you have done with the Nicaraguan site), can AsktheEU.org show an error message if the name the user enters doesn't have a space in it?

Thanks!
Andreas

**Comment by garethrees** [comment]
Code from Nicaragua theme: https://github.com/mysociety/derechoapreguntar-theme/blob/master/lib/model_patches.rb#L39-L44

**Comment by andreaspavlou** [comment]
Great! Since it is not required by law, please can line 42 instead read:

:message => _("Please enter your full name"),

Thanks

Andreas


On 09/05/2016 13:00, Gareth Rees wrote:
>
> Code from Nicaragua theme: 
> https://github.com/mysociety/derechoapreguntar-theme/blob/master/lib/model_patches.rb#L39-L44
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/mysociety/asktheeu-theme/issues/33#issuecomment-217835542>
>




---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus
