### ISSUE TITLE
Google experiments won't run

### ISSUE THREAD

**Issue by lizconlan** [mysociety/asktheeu-theme#34]
Setup currently fails at the last stage of the Google Analytics > Behaviour > Experiments setup process with:

> **Web server rejects utm_expid**  

>To check and display pages in Google Analytics Experiments, we add the URL parameter `utm_expid` to original and variation pages. It seems that your web server won't accept this URL parameter. Change your server to accept parameters, or ask your webmaster for help.

**Comment by garethrees** [comment]
Required for https://github.com/mysociety/asktheeu-theme/pull/26 to work (https://github.com/mysociety/alaveteli-experiments/issues/43).

**Comment by lizconlan** [comment]
Have added bd9c1d1 in case this is an unhelpful error message for "you pasted the javascript into the wrong place"

**Comment by lizconlan** [comment]
Yes, it was that the javascript block needed to be in the HEAD of the page - presumably it was trying to do a redirect from halfway down the page content and failing.
