### ISSUE TITLE
Remove Google Experiment code from theme templates

### ISSUE THREAD

**Issue by lizconlan** [mysociety/asktheeu-theme#52]
Now that the A/B test has been stopped, we don't really need to code cluttering up the theme. May as well remove it the next time we redeploy the site.

Seems to mostly (only?) affect:
- [views/general/frontpage.html.erb](https://github.com/mysociety/asktheeu-theme/blob/master/lib/views/general/frontpage.html.erb)
- [controller_patches.rb](https://github.com/mysociety/asktheeu-theme/blob/master/lib/controller_patches.rb)

**Comment by garethrees** [comment]
Seems like a good thing to do during #51
