### ISSUE TITLE
Re-enable AskTheEU blog

### ISSUE THREAD

**Issue by garethrees** [mysociety/asktheeu-theme#64]
> When you have a moment, it would be great to add the link in the AsktheEU.org main menu to the Blog – in the menu you can just call it ‘Blog’ rather than ‘News and Campaigns’.

**Comment by garethrees** [comment]
Check whether they want a direct link to http://blog.asktheeu.org/, or the feed imported via http://blog.asktheeu.org/feed.

**Comment by lizconlan** [comment]
email sent

**Comment by lizconlan** [comment]
Link to the blog itself in the menu
