### ISSUE TITLE
Upgrade to 0.3x

### ISSUE THREAD

**Issue by lizconlan** [mysociety/asktheeu-theme#66]
- [x] Upgrade theme to 0.32 (current release)
- [ ] Talk to site owners about translations
- [x] Test with `ENABLE_ALAVETELI_PRO` enabled in config
- [ ] Test against 0.33 release candidate (ETA Monday 10/6) and upgrade when full release is made

Part of mysociety/transparency-adessium#3

**Comment by garethrees** [comment]
German translations are up to date.

**Comment by lizconlan** [comment]
(from 0.25)

**Comment by garethrees** [comment]
Upgrade checklist https://docs.google.com/document/d/18cAqOOberBBsuIHzqHEvtOph0fJ1DhKnqgK5G0VtsPk/edit

**Comment by garethrees** [comment]
@gbp think this can be closed?
