### ISSUE TITLE
Adwords for AskTheEU

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/asktheeu-theme#67]
mySociety has been added as an account Manager and I can now set up the Adwords.

This is my proposed plan of action:
1. Set up a campaign named 'English', which will contain ads in English only. This can then be replicated as the ads are translated for other audiences.

2. Begin with a few key Adgroups in the English campaign. Following Adwords best practice, these will be narrowly defined, each based around a single concept.

These concepts will be:
- Obvious ones around FOI and the EU
- The names of the EU bodies combined with keywords around information and FOI
- Anything we glean from Analytics, ie common searches that bring people to the site
- Any major content on the site which we know is of interest - for example, if a large proportion of requests are around a certain topic, we can build an Adgroup about it.

3. Create three ads for each Adgroup. In this way we will be able to see which ads perform the best, and AskTheEU can then use this information to build new ads as they expand the account.

4. Hand over account to AskTheEU. Grant conditions now require that you log into your account a minimum of once a month and that edits are made every 90 days. The lowest-effort way of doing this is to see which keywords are performing badly or need a higher bid, and pause them/increase the bid: this only takes 5 minutes.

If you have more time  you may wish to build more Adgroups based on what is performing well.

Questions for @andreaspavlou and @Gemmamysoc :

1. Do you intend to translate the ads or is that something we might manage? 
2. The account is currently set up to target the UK, Spain, Poland, Germany, France and Italy, ie to appear in those countries' search results. Are you comfortable with the ads being in English for now or should we restrict reach to the UK only until they can be translated?
3. Are there any campaigns or request types which are worth highlighting? As an example, RightToKnow in Australia ran [ads about university admissions](https://github.com/mysociety/alaveteli-experiments/issues/48#issuecomment-234209707), having noticed that this was a common request. I'm thinking maybe salaries, expenses?
4. Which term is most commonly used across the target countries for FOI? Should I be using FOIA, RTK, RTI or any other terms (no problem if so - each can have their own Adgroup)?

**Comment by MyfanwyNixon** [comment]
Additionally: @andreaspavlou could you look into whether AccessInfo would be happy to switch on the 'Search Console' in Analytics? This is what would give insights into which keywords are being used by people who end up on the site. There may be some privacy concerns so Google requires opt-in:


![search console](https://cloud.githubusercontent.com/assets/944656/23946625/0994f160-0973-11e7-87ba-98ec45f7c020.png)

**Comment by andreaspavlou** [comment]
Hi Myf, 

 

So having spoken with Luisa, your plan of action looks great. 

 

When you plan to hand over to AsktheEU, please can we have a phone call with Luisa so that we can ask any immediate questions and you can quickly explain how to change things? If poss/you have time. 

 

Re questions – 

1) We will eventually translate the Ads, but let’s stick to English now so we can see how it works. 

2) Again, it is fine if English language ads turn up in these countries search results (or are we haemorrhaging our funds?) until we decide to translate and we can direct ads to those countries in their languages.

3) In terms of campaigns/request types – we think we could start with Endocrine Disruptors, Glyphosate, refugee crisis, Common Agricultural Policy funding (CAP funding), or cohesion funds/funding might be good to include. 

4) I think that in terms of popularity, the best terms to use would be ‘FOI’ (‘Freedom of Information’), ‘access  to information’ (‘ATI’) and finally ‘access to documents’ 

 

Let us know if you have more questions.

 

Best

 

Andreas 

-- 
Andreas Pavlou
RTI Campaigner & Researcher
Access Info Europe | https://www.access-info.org
Twitter: @andreaspavlou @Access_Info @AsktheEU
Madrid office: +34 913 656 558
Mobile: +34 664 779 124

**Comment by MyfanwyNixon** [comment]
>When you plan to hand over to AsktheEU, please can we have a phone call with Luisa so that we can ask any immediate questions and you can quickly explain how to change things? 

Yes, no problem at all. 

>(or are we haemorrhaging our funds?)
Thanks for the other information. There's no need to worry about hitting the upper limit on the grant yet: 
it may be that searches around 'FOI and the EU' are so rare that we'll have the opposite problem, but we'll cross that bridge as and when it becomes an issue.

Thanks for the other info, all really useful.

**Comment by MyfanwyNixon** [comment]
I have finished setting the Adwords up for the initial phase.

You may have received an email saying that some of the ads had been disapproved because the page they were pointing to is not working: I've asked for a review of this as I believe it's an automated process and the pages work fine for me (they are quite complex URLs though - these are topics pages for the subjects you suggested, eg the Common Agricultural Policy - so maybe that is confusing the system).

Anyway, for the record, I've set up Ad Groups in these basic areas:
- FOI/Access to Information as a basic concept, plus terms like 'how to' and 'FOI request template'
- The name AskTheEU
- Some, but not all of the Bodies the site covers (I was largely led by how many requests each body already had, but if you want to sweep up the 'long tail' then you could work on adding the other bodies in the future)
- The topics you suggested.

There's plenty of room to refine and extend these. As well as adding the other bodies, you could look at:
- Setting up landing pages around topics and bodies, to make an environment where things are explained a little more before the user is thrust into the main site
- Thinking about other ways people might approach the site or the types of search term they might use. I've come from a very obvious stance of listing the bodies, but what if people didn't know what body they needed, just knew they needed some information? What search terms might they use and how could this be reflected in an Ad Group?
- Adding negative keywords: these are search terms which might bring up your ads but which in fact display user needs which aren't met by our site. So for example for TheyWorkForYou we have the negative keyword 'MP3' because without it, Google was including it in more generic MP Ad Groups.
- Adding tracking to link up your Adwords account with your Analytics one - that way you'll be able to see whether people clicking on an ad are actually going on to make a request, or how many pages they are viewing, etc
- Checking quality scores: once the ads have been running for a couple of weeks, check these to see if there are improvements that could be made
- Checking the URLs I've used for the topics: perhaps you'd prefer that these included/excluded unsuccessful requests, etc.

I'm happy to go through all this in a Hangout with some screensharing - let me know when suits.

**Comment by andreaspavlou** [comment]
Hi Myf, 

Thanks for setting this all up! You have made some good points about how to refine the ads, so we will definitely need to this about this when creating/adapting future ones. 

Would Monday 3rd April work for a screen-sharing sesh?

Andreas



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by garethrees** [comment]
Sounds like this was done to some level. Closing.
