### ISSUE TITLE
Filtering the authorities shows 0 results

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/asktheeu-theme#68]
From https://www.asktheeu.org/en/body/list/all, clicking on any of the categories in the left hand column, eg https://www.asktheeu.org/en/body?tag=european_parliament, brings up no results.

**Comment by lizconlan** [comment]
Another example:

https://www.asktheeu.org/en/body?tag=ec_dg <-- broken
https://www.asktheeu.org/en/body/list/ec_dg <-- works

**Comment by lizconlan** [comment]
Appears to be a theme issue as the code works as expected when the theme is disabled

**Comment by lizconlan** [comment]
To do - check whether the controller override introduced in https://github.com/mysociety/asktheeu-theme/commit/ce7d145ae0770f142fe7ec26f4b0748dcccc3a22 is still needed (we think it doesn't get called any more except via the category link) and either 

* keep the existing PR code (with a note on why this is required)
* remove the override (and any tests) with a note about having done so

**Comment by lizconlan** [comment]
Ah, looks like the old frontpage used to have a list of public bodies with helpful comment "this is too slow", that's probably what the workaround was for

https://github.com/mysociety/alaveteli/blob/6d5390372a4515db3a7e9bb02831d379a468c4ee/app/controllers/general_controller.rb#L31-L46
