### ISSUE TITLE
Remove What is a campaign page? section on help/requesting

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/asktheeu-theme#69]
At the foot of https://www.asktheeu.org/en/help/requesting#widgets-and-campaigns, the link "You can create a special campaign page by simply fill in the form" leads to a 404.

**Comment by garethrees** [comment]
@andreaspavlou looks like that [blog post](http://blog.asktheeu.org/2015/04/create-your-own-campaign-page/) might have gone missing with the blog upgrade?

**Comment by andreaspavlou** [comment]
Hi Gareth, 

We have taken it down as we do not want to do these kind of campaigns any more. We prefer to curate material that might reference campaigns people are doing, more like the whatdotheyknow blog.

**Comment by garethrees** [comment]
Cool. Want us to remove that last line, or the whole section?

**Comment by andreaspavlou** [comment]
In fact you can remove that whole question as it is irrelevant J  thanks

Andreas 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
