### ISSUE TITLE
Mention Pro embargoes on the help page

### ISSUE THREAD

**Issue by lizconlan** [mysociety/asktheeu-theme#95]
The `help/requesting` page (translated into German and Spanish) currently has a section that deals with keeping requests confidential until an article is published. This should be updated when the Pro features are added.

Current content:

> \<h2\>Can I keep my request confidential until I release my story/article?\</h2\>
\<p\>AsktheEU.org is designed for public requests. All responses that we receive are automatically published on the website for anyone to read.\</p\>
\<p\>If you are a journalist, NGO, or other person who wants to keep the answer private until you have written your story or for other reasons, please get in contact with us.\</p\>

**Comment by garethrees** [comment]
We'll update the en page to the above and just notify them that we've added this and that they can send us translations if they wish
