### ISSUE TITLE
Add pro T&Cs page

### ISSUE THREAD

**Issue by garethrees** [mysociety/asktheeu-theme#96]
Required by #77

Override `app/views/alaveteli_pro/pages/legal.html.erb` and `app/views/alaveteli_pro/pages/_legal.html.erb` in the theme to add their T&Cs

**Comment by gbp** [comment]
Initial [stubs](https://github.com/mysociety/asktheeu-theme/compare/master...mysociety:96-legal-pages) ready for copy when provided.

**Comment by garethrees** [comment]
https://drive.google.com/drive/u/1/folders/1og215dHuQGCVi0Rerubze9uoVyAiv1a3
